name: Test whether the dockerized versions work (with secrets)

on:
  push:
  pull_request:
    branches: [main, releases/**]

jobs:
  test-docker-compose:
    name: verify docker-compose setup
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Start postgres databases in docker-compose
        run: docker compose up -d

      - name: Verify that mapmatching database is up and can be connected to
        uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
        env:
          POSTGRES_USER: username
          POSTGRES_DB: testdb
          PGPASSWORD: password
        with:
          command:
            'psql -h localhost -p 6432 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c
            "SELECT ''OK'';"'

      - name: Verify that azuredbmock database is up and can be connected to
        uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
        env:
          POSTGRES_USER: username
          POSTGRES_DB: testdb
          PGPASSWORD: password
        with:
          command:
            'psql -h localhost -p 7432 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c
            "SELECT ''OK'';"'
